# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPAs by redirecting everything to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200